# Generated by Django 4.2.10 on 2026-05-08 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(help_text='Human-readable address or region name', max_length=255)),
                ('soil_type', models.CharField(blank=True, default='', max_length=100)),
                ('climate_zone', models.CharField(blank=True, default='', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Farm centroid latitude (decimal degrees, WGS-84)', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Farm centroid longitude (decimal degrees, WGS-84)', max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('crop_type', models.CharField(max_length=100)),
                ('area', models.FloatField()),
                ('moisture', models.FloatField()),
                ('harvest_date', models.DateField()),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('alert', 'Alert')], default='healthy', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Plot centre latitude (decimal degrees, WGS-84)', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Plot centre longitude (decimal degrees, WGS-84)', max_digits=9, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='farms.farm')),
            ],
        ),
        migrations.CreateModel(
            name='SoilRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitrogen', models.FloatField()),
                ('phosphorus', models.FloatField()),
                ('potassium', models.FloatField()),
                ('ph', models.FloatField()),
                ('moisture', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_records', to='farms.plot')),
            ],
        ),
        migrations.CreateModel(
            name='IrrigationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField()),
                ('water_volume', models.FloatField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigations', to='farms.plot')),
            ],
        ),
        migrations.CreateModel(
            name='FarmData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('nitrogen', models.FloatField(blank=True, null=True)),
                ('phosphorus', models.FloatField(blank=True, null=True)),
                ('potassium', models.FloatField(blank=True, null=True)),
                ('soil_ph', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_data', to='farms.farm')),
            ],
        ),
        migrations.CreateModel(
            name='CropField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(choices=[('wheat', 'Wheat'), ('corn', 'Corn'), ('rice', 'Rice'), ('barley', 'Barley'), ('soybeans', 'Soybeans'), ('cotton', 'Cotton'), ('sugarcane', 'Sugarcane'), ('other', 'Other')], db_index=True, default='wheat', max_length=50)),
                ('color', models.CharField(default='#00AA00', help_text='Hex color code for map visualization (e.g., #FF5733)', max_length=7)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Field center latitude (decimal degrees, WGS-84)', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Field center longitude (decimal degrees, WGS-84)', max_digits=9)),
                ('area', models.FloatField(help_text='Field area in hectares')),
                ('soil_type', models.CharField(blank=True, default='', help_text='Type of soil (loamy, sandy, clay, etc.)', max_length=100)),
                ('ndvi', models.FloatField(blank=True, help_text='Normalized Difference Vegetation Index (-1 to 1)', null=True)),
                ('soil_moisture', models.FloatField(blank=True, help_text='Soil moisture percentage (0-100)', null=True)),
                ('temperature', models.FloatField(blank=True, help_text='Average temperature in Celsius', null=True)),
                ('humidity', models.FloatField(blank=True, help_text='Relative humidity percentage (0-100)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crop_fields', to='farms.farm')),
            ],
            options={
                'indexes': [models.Index(fields=['crop_type', 'farm'], name='farms_cropf_crop_ty_fcb43b_idx'), models.Index(fields=['latitude', 'longitude'], name='farms_cropf_latitud_2e925d_idx')],
            },
        ),
    ]
