# Generated by Django 4.2.10 on 2026-05-08 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AICoreResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('cv', 'Computer Vision'), ('crop_rotation', 'Crop Rotation'), ('crop_recommendation', 'Crop Recommendation'), ('chatbot', 'Chatbot'), ('price_forecasting', 'Price Forecasting'), ('scenario_simulator', 'Scenario Simulator'), ('soil_health_prediction', 'Soil Health Prediction'), ('fertilizer_optimizer', 'Fertilizer Optimizer'), ('irrigation_optimizer', 'Irrigation Optimizer'), ('yield_prediction', 'Yield Prediction')], db_index=True, help_text='Type of AI model used', max_length=50)),
                ('input_data', models.JSONField(help_text='Input parameters sent to the model')),
                ('result_data', models.JSONField(help_text='Output predictions from the model')),
                ('execution_time', models.FloatField(blank=True, help_text='Time taken to run prediction in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when prediction was made')),
            ],
            options={
                'verbose_name': 'AI Core Result',
                'verbose_name_plural': 'AI Core Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CropField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.CharField(db_index=True, max_length=80)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('crop', models.CharField(db_index=True, max_length=50)),
                ('year', models.IntegerField(db_index=True)),
                ('harv_area', models.FloatField(blank=True, null=True)),
                ('soil_ph', models.FloatField(blank=True, null=True)),
                ('soil_soc', models.FloatField(blank=True, null=True)),
                ('soil_clay', models.FloatField(blank=True, null=True)),
                ('soil_sand', models.FloatField(blank=True, null=True)),
                ('soil_silt', models.FloatField(blank=True, null=True)),
                ('soil_nitrogen', models.FloatField(blank=True, null=True)),
                ('soil_cec', models.FloatField(blank=True, null=True)),
                ('soil_bd', models.FloatField(blank=True, null=True)),
                ('soil_cfvo', models.FloatField(blank=True, null=True)),
                ('soil_ocd', models.FloatField(blank=True, null=True)),
                ('temp_mean', models.FloatField(blank=True, null=True)),
                ('precip_sum', models.FloatField(blank=True, null=True)),
                ('aet_mean', models.FloatField(blank=True, null=True)),
                ('pet_mean', models.FloatField(blank=True, null=True)),
                ('vpd_mean', models.FloatField(blank=True, null=True)),
                ('soil_moisture', models.FloatField(blank=True, null=True)),
                ('ndvi_mean', models.FloatField(blank=True, null=True)),
                ('ndvi_max', models.FloatField(blank=True, null=True)),
                ('ndvi_min', models.FloatField(blank=True, null=True)),
                ('ndvi_amplitude', models.FloatField(blank=True, null=True)),
                ('evi_mean', models.FloatField(blank=True, null=True)),
                ('lswi_mean', models.FloatField(blank=True, null=True)),
                ('ndre_mean', models.FloatField(blank=True, null=True)),
                ('ndre_max', models.FloatField(blank=True, null=True)),
                ('sar_vv_mean', models.FloatField(blank=True, null=True)),
                ('sar_vh_mean', models.FloatField(blank=True, null=True)),
                ('sar_vv_vh_ratio', models.FloatField(blank=True, null=True)),
                ('soil_texture_class', models.CharField(blank=True, max_length=20, null=True)),
                ('fertility_index', models.FloatField(blank=True, null=True)),
                ('aridity_index', models.FloatField(blank=True, null=True)),
                ('water_balance', models.FloatField(blank=True, null=True)),
                ('rice_sar_signal', models.FloatField(blank=True, null=True)),
                ('maize_sar_signal', models.FloatField(blank=True, null=True)),
                ('wheat_sar_signal', models.FloatField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Monthly Sentinel-2 and SAR index columns (ndvi_m01…sar_vh_m12 etc.)')),
            ],
            options={
                'verbose_name': 'Crop Field',
                'verbose_name_plural': 'Crop Fields',
                'ordering': ['field_id', 'year'],
                'indexes': [models.Index(fields=['crop', 'year'], name='ai_core_cro_crop_6b1671_idx'), models.Index(fields=['lat', 'lon'], name='ai_core_cro_lat_c8f5d3_idx'), models.Index(fields=['field_id', 'year'], name='ai_core_cro_field_i_eb8faf_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='cropfield',
            constraint=models.UniqueConstraint(fields=('field_id', 'year', 'crop'), name='unique_field_year_crop'),
        ),
        migrations.AddField(
            model_name='aicoreresult',
            name='farm',
            field=models.ForeignKey(blank=True, help_text='Farm associated with this prediction (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_results', to='farms.farm'),
        ),
        migrations.AddField(
            model_name='aicoreresult',
            name='user',
            field=models.ForeignKey(help_text='User who requested the prediction', on_delete=django.db.models.deletion.CASCADE, related_name='ai_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='aicoreresult',
            index=models.Index(fields=['user', '-created_at'], name='ai_core_aic_user_id_f3ea20_idx'),
        ),
        migrations.AddIndex(
            model_name='aicoreresult',
            index=models.Index(fields=['model_type', '-created_at'], name='ai_core_aic_model_t_7f7ca2_idx'),
        ),
        migrations.AddIndex(
            model_name='aicoreresult',
            index=models.Index(fields=['farm', '-created_at'], name='ai_core_aic_farm_id_d2f695_idx'),
        ),
    ]
